ALTER TABLE plays ADD COLUMN trade_price DOUBLE PRECISION NOT NULL;
ALTER TABLE plays ADD COLUMN mark DOUBLE PRECISION NOT NULL;
ALTER TABLE plays ADD COLUMN close_price DOUBLE PRECISION NOT NULL;
CREATE OR REPLACE FUNCTION set_updated_at_to_now() RETURNS TRIGGER AS $$BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;$$ language PLPGSQL;
